packages:
  - chrome-extension
  - pages/*
  - packages/*
  - tests/*

catalog:
  autoprefixer: ^10.4.21
  postcss: ^8.5.3
  tailwindcss: ^3.4.17

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - edgedriver
  - esbuild
  - geckodriver
  - unrs-resolver
